language: php

dist: trusty

sudo: false

php:
  - 7.0
  - 7.1

env:
  global:
    - OC_DB_HOSTNAME=localhost
    - OC_DB_USERNAME=root
    - OC_DB_PASSWORD=root
    - OC_DB_DATABASE=tests_opencart
    - OC_DB_DRIVER=mysqli
    - OC_USERNAME=admin
    - OC_PASSWORD=admin
    - OC_EMAIL=test@test.com
    - SERVER_PORT=8000
    - SERVER_URL=http://localhost

stages:
  - test
  - build
  - deploy

before_script: make before_script

script: composer test

jobs:
  include:
    - stage: build
      before_script: skip
      script: make build_archive
    - stage: deploy
      before_script: skip
      before_deploy: make tag
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file: $ARCHIVE_NAME
      if: (branch = master) AND (type = push) AND (fork = true)
      after_deploy: make delete_archive