language: php

dist: trusty

sudo: false

php:
  - 7.0
  - 7.1

env:
  global:
    - ROBO_CONFIG=$(TRAVIS_BUILD_DIR)/tests/robo.yml
    - OC_DB_HOSTNAME=localhost
    - OC_DB_USERNAME=root
    - OC_DB_PASSWORD=root
    - OC_DB_DATABASE=tests_opencart
    - OC_DB_DRIVER=mysqli
    - OC_USERNAME=admin
    - OC_PASSWORD=admin
    - OC_EMAIL=test@test.com
    - SERVER_PORT=8000
    - SERVER_URL=http://localhost

stages:
  - test
  - deploy

before_script: make before_script

script: composer test

jobs:
  include:
    - stage: deploy
      script: make build_archive
      before_deploy:
        - export VERSION=`cat VERSION`
        - export ARCHIVE_NAME='/tmp/retailcrm-'$(VERSION)'.zip'
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file: $ARCHIVE_NAME
        on:
          branch: master